#!/usr/bin/with-contenv bash

# copy cronjob to /config
[[ ! -e /config/backup ]] && \
cp /defaults/backup /config/backup

# set cron job
crontab /config/backup

# permissions
chown -R abc:abc \
	/config
chown abc:abc \
	/backup
